info:
  contact: {}
paths:
  /order/menu:
    get:
      description: 등록된 메뉴 전체의 리스트를 가져올 수 있다.
      responses: {}
      summary: call GetMenu, return ok by json.
  /order/menu/:name:
    get:
      description: 메뉴의 이름을 파라미터로 받아 해당 메뉴의 정보를 가져오는 기능
      responses: {}
      summary: call GetMenuWithName, return ok by json.
swagger: "2.0"
