info:
  contact: {}
paths:
  /menu:
    get:
      description: 등록된 메뉴 리스트를 가져온다.
      responses: {}
      summary: call GetMenuList, return ok by json.
    post:
      consumes:
      - application/json
      description: 메뉴의 정보를 JSON으로 입력받아 등록한다.
      produces:
      - application/json
      responses: {}
      summary: call RegisterMenu, return ok by json.
  /menu/:id:
    delete:
      description: 메뉴의 아이디를 파라미터로 받아 해당 메뉴를 삭제하는 기능
      responses: {}
      summary: call DelMenu, return ok by json.
    put:
      description: 메뉴의 아이디를 파라미터로 받고 JSON으로 수정하려는 내용을 받아 기존 메뉴의 정보를 변경할 수 있다.
      responses: {}
      summary: call UpdateMenu, return ok by json.
swagger: "2.0"
